version: '3.8'
services:
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./app/server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - server_data:/app/data

  nginx:
    build: ./app/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - server
    volumes:
      - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/nginx/certs:/etc/nginx/certs:ro
    environment:
      - NGINX_HOST=jgsnapp.ru
      - NGINX_PORT=80
      - NGINX_SSL_PORT=443

volumes:
  server_data:
